<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWindowsForms>true</UseWindowsForms><UseWPF>true</UseWPF><AssemblyName>RemoteDebugger.Lab</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="../../src/RemoteDebugger/RemoteDebugger.csproj"/></ItemGroup></Project>
