<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWindowsForms>true</UseWindowsForms><UseWPF>true</UseWPF><ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode><AssemblyName>RemoteDebugger</AssemblyName><ApplicationManifest>app.manifest</ApplicationManifest><ApplicationIcon>Assets\RemoteDebugger.ico</ApplicationIcon></PropertyGroup><ItemGroup><ProjectReference Include="../RemoteDebugger.Core/RemoteDebugger.Core.csproj" /><EmbeddedResource Include="Assets\RemoteDebugger.ico" LogicalName="RemoteDebugger.Assets.RemoteDebugger.ico" /></ItemGroup></Project>
