/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ae2d6bcafcdef3939b201b06bf3dd8dc)
interface __BaseEnv_Env {
	PROTOCOL: "remote-debugger-relay-v1";
	SESSIONS: DurableObjectNamespace<import("./src/index").SupportSession>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "SupportSession";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PROTOCOL">> {}
}
