/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: cba2a25fc5c8bec70c876f5652c3f8ff)
interface __BaseEnv_Env {
	PROTOCOL: "remote-debugger-relay-v1";
	SESSIONS: DurableObjectNamespace<import("./src/index").SupportSession>;
	DIRECTORY: DurableObjectNamespace<import("./src/index").ClientDirectory>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "SupportSession" | "ClientDirectory";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PROTOCOL">> {}
}
